#!/usr/bin/python

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci_range():
  fib = [1, 2]
  while fib[-1] <= 4000000:
    fib.append(fib[-2] + fib[-1])
  return fib

even_numbers_from = lambda n: n % 2 == 0
only              = lambda f, i: sum(filter(f, i))

print only(even_numbers_from, fibonacci_range())

